customer_support_dbt:
  outputs:
    dev:
      account: gsvvwno-ts70298
      database: SUPPORT_INTEL_DB
      private_key_path: /Users/saiootejreddy/.snowflake/rsa_key.p8
      role: DBT_ROLE
      schema: DBT_SCHEMA
      threads: 1
      type: snowflake
      user: HASHIRAMASENJU2
      warehouse: SUPPORT_DEV_WH
  target: dev
